framework:
    workflows:
        ally_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                 type: 'method'
                 property: 'currentPlace'
            supports:
                 - App\Entity\CardTypes\AllyCard
            initial_marking: draw_deck
            places:
                - draw_deck
                - hand
                - in_play
                - discard_pile
                - dead_pile
            transitions:
                draw_card:
                    from: draw_deck
                    to: hand
                play_card:
                    from: [hand,discard_pile]
                    to: in_play
                activate_ability:
                    from: in_play
                    to: in_play
                discard_card:
                    from: [draw_deck,hand,in_play]
                    to: discard_pile
                wound:
                    from: in_play
                    to: in_play
                exert:
                    from: in_play
                    to: in_play
                heal:
                    from: in_play
                    to: in_play
                overwhelm:
                    from: in_play
                    to: dead_pile
                kill:
                    from: in_play
                    to: dead_pile
                put_back:
                    from: [hand,discard_pile]
                    to: draw_deck
                take_back:
                    from: discard_pile
                    to: hand
        artifact_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                 type: 'method'
                 property: 'currentPlace'
            supports:
                 - App\Entity\CardTypes\ArtifactCard
            initial_marking: draw_deck
            places:
                - draw_deck
                - hand
                - in_play
                - discard_pile
            transitions:
                draw_card:
                    from: draw_deck
                    to: hand
                play_card:
                    from: [hand,discard_pile]
                    to: in_play
                activate_ability:
                    from: in_play
                    to: in_play
                discard_card:
                    from: [draw_deck,hand,in_play]
                    to: discard_pile
                put_back:
                    from: [hand,discard_pile]
                    to: draw_deck
                take_back:
                    from: discard_pile
                    to: hand
        companion_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                 type: 'method'
                 property: 'currentPlace'
            supports:
                 - App\Entity\CardTypes\CompanionCard
            initial_marking: draw_deck
            places:
                - draw_deck
                - hand
                - in_play
                - discard_pile
                - dead_pile
            transitions:
                start_fellowship:
                    from: draw_deck
                    to: in_play
                draw_card:
                    from: draw_deck
                    to: hand
                play_card:
                    from: [hand,discard_pile]
                    to: in_play
                activate_ability:
                    from: in_play
                    to: in_play
                discard_card:
                    from: [draw_deck,hand,in_play]
                    to: discard_pile
                wound:
                    from: in_play
                    to: in_play
                exert:
                    from: in_play
                    to: in_play
                heal:
                    from: in_play
                    to: in_play
                overwhelm:
                    from: in_play
                    to: dead_pile
                kill:
                    from: in_play
                    to: dead_pile
                put_back:
                    from: [hand,discard_pile]
                    to: draw_deck
                take_back:
                    from: discard_pile
                    to: hand
        condition_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                 type: 'method'
                 property: 'currentPlace'
            supports:
                 - App\Entity\CardTypes\ConditionCard
            initial_marking: draw_deck
            places:
                - draw_deck
                - hand
                - in_play
                - discard_pile
            transitions:
                draw_card:
                    from: draw_deck
                    to: hand
                play_card:
                    from: [hand,discard_pile]
                    to: in_play
                activate_ability:
                    from: in_play
                    to: in_play
                discard_card:
                    from: [draw_deck,hand,in_play]
                    to: discard_pile
                put_back:
                    from: [hand,discard_pile]
                    to: draw_deck
                take_back:
                    from: discard_pile
                    to: hand
        event_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                 type: 'method'
                 property: 'currentPlace'
            supports:
                 - App\Entity\CardTypes\EventCard
            initial_marking: draw_deck
            places:
                - draw_deck
                - hand
                - discard_pile
            transitions:
                draw_card:
                    from: draw_deck
                    to: hand
                play_card:
                    from: [hand,discard_pile]
                    to: discard_pile
                discard_card:
                    from: [draw_deck,hand]
                    to: discard_pile
                put_back:
                    from: [hand,discard_pile]
                    to: draw_deck
                take_back:
                    from: discard_pile
                    to: hand
        minion_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                 type: 'method'
                 property: 'currentPlace'
            supports:
                 - App\Entity\CardTypes\MinionCard
            initial_marking: draw_deck
            places:
                - draw_deck
                - hand
                - in_play
                - discard_pile
            transitions:
                draw_card:
                    from: draw_deck
                    to: hand
                play_card:
                    from: [hand,discard_pile]
                    to: in_play
                activate_ability:
                    from: in_play
                    to: in_play
                discard_card:
                    from: [draw_deck,hand,in_play]
                    to: discard_pile
                wound:
                    from: in_play
                    to: in_play
                exert:
                    from: in_play
                    to: in_play
                heal:
                    from: in_play
                    to: in_play
                overwhelm:
                    from: in_play
                    to: discard_pile
                put_back:
                    from: [hand,discard_pile]
                    to: draw_deck
                take_back:
                    from: discard_pile
                    to: hand
        possession_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                 type: 'method'
                 property: 'currentPlace'
            supports:
                 - App\Entity\CardTypes\PossessionCard
            initial_marking: draw_deck
            places:
                - draw_deck
                - hand
                - in_play
                - discard_pile
            transitions:
                draw_card:
                    from: draw_deck
                    to: hand
                play_card:
                    from: [hand,discard_pile]
                    to: in_play
                activate_ability:
                    from: in_play
                    to: in_play
                discard_card:
                    from: [draw_deck,hand,in_play]
                    to: discard_pile
                put_back:
                    from: [hand,discard_pile]
                    to: draw_deck
                take_back:
                    from: discard_pile
                    to: hand
        site_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                 type: 'method'
                 property: 'currentPlace'
            supports:
                 - App\Entity\CardTypes\SiteCard
            initial_marking: adventure_deck
            places:
                - adventure_deck
                - adventure_path
            transitions:
                place_site:
                    from: adventure_deck
                    to: adventure_path
                activate_ability:
                    from: adventure_path
                    to: adventure_path
                replace_site:
                    from: adventure_path
                    to: adventure_deck
        ring_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                 type: 'method'
                 property: 'currentPlace'
            supports:
                 - App\Entity\CardTypes\RingCard
            initial_marking: in_play
            places:
                - in_play
            transitions:
                empty:
                    from: in_play
                    to: in_play
        game:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                 type: 'method'
                 property: 'currentPlace'
            supports:
                 - App\Entity\Game
            initial_marking: join_game
            places:
                join_game:
                bid_tokens:
                choose_fellowship:
                resolve_turn_start:
                resolve_fellowship_start:
                perform_fellowship_actions_freeps:
                resolve_move_triggers_freeps:
                resolve_shadow_start:
                perform_shadow_actions_shadow:
                resolve_maneuver_start:
                perform_maneuver_actions:
                resolve_archery_start:
                perform_archery_actions:
                resolve_archery_fire:
                resolve_assignment_start:
                perform_assignment_actions:
                assign_defenders_freeps:
                assign_attackers_shadow:
                choose_skirmish_freeps:
                resolve_skirmish_start:
                perform_skirmish_actions:
                resolve_skirmish_end:
                resolve_regroup_start:
                perform_regroup_actions:
                reconcile_hand_shadow:
                choose_move_again_freeps:
                reconcile_hand_freeps:
                resolve_turn_end:
                finished:
            transitions:
                start_game:
                    from: join_game
                    to: bid_tokens
                    metadata:
                        auto: true
                complete_bid:
                    from: bid_tokens
                    to: choose_fellowship
                    metadata:
                        auto: true
                start_turn:
                    from: choose_fellowship
                    to: resolve_turn_start
                    metadata:
                        auto: true
                start_fellowship:
                    from: resolve_turn_start
                    to: resolve_fellowship_start
                fellowship:
                    from: resolve_fellowship_start
                    to: perform_fellowship_actions_freeps
                move:
                    from: perform_fellowship_actions_freeps
                    to: resolve_move_triggers_freeps
                start_shadow:
                    from: resolve_move_triggers_freeps
                    to: resolve_shadow_start
                shadow:
                    from: resolve_shadow_start
                    to: perform_shadow_actions_shadow
                start_maneuver:
                    from: perform_shadow_actions_shadow
                    to: resolve_maneuver_start
                no_minions:
                    from: [perform_shadow_actions_shadow, perform_maneuver_actions, resolve_archery_fire]
                    to: resolve_regroup_start
                maneuver:
                    from: resolve_maneuver_start
                    to: perform_maneuver_actions
                start_archery:
                    from: perform_maneuver_actions
                    to: resolve_archery_start
                archery:
                    from: resolve_archery_start
                    to: perform_archery_actions
                archery_fire:
                    from: perform_archery_actions
                    to: resolve_archery_fire
                start_assignment:
                    from: resolve_archery_fire
                    to: resolve_assignment_start
                assignment:
                    from: resolve_assignment_start
                    to: perform_assignment_actions
                assign_defenders:
                    from: perform_assignment_actions
                    to: assign_defenders_freeps
                assign_attackers:
                    from: assign_defenders_freeps
                    to: assign_attackers_shadow
                all_assigned:
                    from: [assign_defenders_freeps, assign_attackers_shadow]
                    to: choose_skirmish_freeps
                start_skirmish:
                    from: choose_skirmish_freeps
                    to: resolve_skirmish_start
                skirmish:
                    from: resolve_skirmish_start
                    to: perform_skirmish_actions
                resolve_skirmish:
                    from: perform_skirmish_actions
                    to: resolve_skirmish_end
                next_skirmish:
                    from: resolve_skirmish_end
                    to: choose_skirmish_freeps
                fierce_minions:
                    from: resolve_skirmish_end
                    to: resolve_assignment_start
                start_regroup:
                    from: resolve_skirmish_end
                    to: resolve_regroup_start
                regroup:
                    from: resolve_regroup_start
                    to: perform_regroup_actions
                reconcile_shadow:
                    from: perform_regroup_actions
                    to: reconcile_hand_shadow
                move_decision:
                    from: reconcile_hand_shadow
                    to: choose_move_again_freeps
                game_over:
                    from: reconcile_hand_shadow
                    to: finished
                stop:
                    from: choose_move_again_freeps
                    to: reconcile_hand_freeps
                move_again:
                    from: choose_move_again_freeps
                    to: resolve_shadow_start
                end_of_turn:
                    from: reconcile_hand_freeps
                    to: resolve_turn_end
                next_turn:
                    from: resolve_turn_end
                    to: resolve_turn_start
