framework:
    workflows:
        conflict_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentPlace'
            supports:
                - App\Entity\CardTypes\ConflictCard
            initial_marking: conflict_draw_deck
            places:
                - !php/const App\Entity\CardTypes\ConflictCard::STATE_DRAW_DECK
                - !php/const App\Entity\CardTypes\ConflictCard::STATE_HAND
                - !php/const App\Entity\CardTypes\ConflictCard::STATE_IN_PLAY
                - !php/const App\Entity\CardTypes\ConflictCard::STATE_DISCARD_PILE
            transitions:
                draw_card:
                    from: conflict_draw_deck
                    to: hand
                play_card:
                    from: [hand,conflict_discard_pile]
                    to: in_play
                discard_card:
                    from: [conflict_draw_deck,hand,in_play]
                    to: conflict_discard_pile
                put_back:
                    from: [hand,conflict_discard_pile]
                    to: conflict_draw_deck
                take_back:
                    from: conflict_discard_pile
                    to: hand