framework:
    workflows:
        dynasty_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentPlace'
            supports:
                - App\Entity\CardTypes\DynastyCard
            initial_marking: dynasty_draw_deck
            places:
                - !php/const App\Entity\CardTypes\DynastyCard::STATE_DRAW_DECK
                - !php/const App\Entity\CardTypes\DynastyCard::STATE_PROVINCE_FACEDOWN
                - !php/const App\Entity\CardTypes\DynastyCard::STATE_PROVINCE_FACEUP
                - !php/const App\Entity\CardTypes\DynastyCard::STATE_IN_PLAY
                - !php/const App\Entity\CardTypes\DynastyCard::STATE_DISCARD_PILE
            transitions:
                draw_card:
                    from: !php/const App\Entity\CardTypes\DynastyCard::STATE_DRAW_DECK
                    to: !php/const App\Entity\CardTypes\DynastyCard::STATE_PROVINCE_FACEDOWN
                turn_faceup:
                    from: !php/const App\Entity\CardTypes\DynastyCard::STATE_PROVINCE_FACEDOWN
                    to: !php/const App\Entity\CardTypes\DynastyCard::STATE_PROVINCE_FACEUP
                turn_facedown:
                    from: !php/const App\Entity\CardTypes\DynastyCard::STATE_PROVINCE_FACEUP
                    to: !php/const App\Entity\CardTypes\DynastyCard::STATE_PROVINCE_FACEDOWN
                play:
                    from: !php/const App\Entity\CardTypes\DynastyCard::STATE_PROVINCE_FACEUP
                    to: !php/const App\Entity\CardTypes\DynastyCard::STATE_IN_PLAY
                discard:
                    from: !php/const App\Entity\CardTypes\DynastyCard::STATE_IN_PLAY
                    to: !php/const App\Entity\CardTypes\DynastyCard::STATE_DISCARD_PILE
