framework:
    workflows:
        dynasty_card:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentPlace'
            supports:
                - App\Entity\CardTypes\DynastyCard
            initial_marking: dynasty_draw_deck
            places:
                - dynasty_draw_deck
                - hand
                - in_play
                - dynasty_discard_pile
            transitions:
                draw_card:
                    from: dynasty_draw_deck
                    to: hand
                play_card:
                    from: [hand,dynasty_discard_pile]
                    to: in_play
                discard_card:
                    from: [dynasty_draw_deck,hand,in_play]
                    to: dynasty_discard_pile
                put_back:
                    from: [hand,dynasty_discard_pile]
                    to: dynasty_draw_deck
                take_back:
                    from: dynasty_discard_pile
                    to: hand