framework:
    workflows:
        game:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentPlace'
            supports:
                - App\Entity\Game
            initial_marking: join_game
            transitions:
                start_game:
                    from: join_game
                    to: dynasty_phase_begins
                    metadata:
                        auto: true
                t0:
                    from: dynasty_phase_begins
                    to: reveal_facedown_dynasty_cards
                    metadata:
                        auto: true
                t1:
                    from: reveal_facedown_dynasty_cards
                    to: collect_fate
                    metadata:
                        auto: true
                t2:
                    from: collect_fate
                    to: play_cards_from_provinces
                    metadata:
                        auto: true
                t3:
                    from: play_cards_from_provinces
                    to: dynasty_phase_ends
                t4:
                    from: dynasty_phase_ends
                    to: draw_phase_begins
                t5:
                    from: draw_phase_begins
                    to: honor_bid
                t6:
                    from: honor_bid
                    to: reveal_honor_dials
                t7:
                    from: reveal_honor_dials
                    to: transfer_honor
                t8:
                    from: transfer_honor
                    to: draw_cards
                t9:
                    from: draw_cards
                    to: draw_phase_ends
                t10:
                    from: draw_phase_ends
                    to: conflict_phase_begins
                t11:
                    from: conflict_phase_begins
                    to: declare_conflict
                t12:
                    from: declare_conflict
                    to: declare_defenders
                t13:
                    from: declare_defenders
                    to: conflict_action_window
                t14:
                    from: conflict_action_window
                    to: determine_result
                t15:
                    from: determine_result
                    to: apply_unopposed
                t16:
                    from: apply_unopposed
                    to: break_province
                t17:
                    from: break_province
                    to: resolve_ring_effects
                t18:
                    from: resolve_ring_effects
                    to: claim_ring
                t19:
                    from: claim_ring
                    to: return_home
                t20:
                    from: return_home
                    to: conflict_ends
                t21:
                    from: conflict_ends
                    to: declare_conflict
                t22:
                    from: conflict_phase_begins
                    to: determine_imperial_favor
                t23:
                    from: conflict_ends
                    to: determine_imperial_favor
                t24:
                    from: determine_imperial_favor
                    to: glory_count
                t25:
                    from: glory_count
                    to: claim_imperial_favor
                t26:
                    from: claim_imperial_favor
                    to: conflict_phase_ends
                t27:
                    from: conflict_phase_ends
                    to: fate_phase_begins
                t28:
                    from: fate_phase_begins
                    to: discard_characters_with_no_fate
                t29:
                    from: discard_characters_with_no_fate
                    to: remove_fate_from_characters
                t30:
                    from: remove_fate_from_characters
                    to: place_fate_on_unclaimed_rings
                t31:
                    from: place_fate_on_unclaimed_rings
                    to: ready_cards
                t32:
                    from: ready_cards
                    to: discard_from_provinces
                t33:
                    from: discard_from_provinces
                    to: return_rings
                t34:
                    from: return_rings
                    to: pass_first_player_token
                t35:
                    from: pass_first_player_token
                    to: fate_phase_ends
                t36:
                    from: fate_phase_ends
                    to: dynasty_phase_begins




