@startuml
hide empty description

state bidding_fork <<fork>>
state bidding {
    state bidding_p1_in_progress
    state bidding_p2_in_progress
    state bidding_p1_done
    state bidding_p2_done
}
state setup_fork <<fork>>
state setup {
    state choosing_fellowship_p1_in_progress
    state choosing_fellowship_p2_in_progress
    state choosing_fellowship_p1_done
    state choosing_fellowship_p2_done
}
state start_turn_fork <<fork>>
state start_turn {
    state resolve_start_turn_triggers_fp_in_progress
}
state fellowship_fork <<fork>>
state fellowship {
    state resolve_start_fellowship_triggers_fp_in_progress
    state fellowship_actions_fp_in_progress
    state resolve_move_triggers_fp_in_progress
}
state shadow_fork <<fork>>
state shadow {
    state shadow_actions_sp_in_progress
}
state maneuver_fork <<fork>>
state maneuver {
    state maneuver_actions_fp_in_progress
    state maneuver_actions_sp_in_progress
    state maneuver_actions_fp_done
    state maneuver_actions_sp_done
}
state archery_fork <<fork>>
state archery {
    state archery_actions_fp_in_progress
    state archery_actions_sp_in_progress
    state archery_actions_fp_done
    state archery_actions_sp_done
    state archery_fire_fp_in_progress
    state archery_fire_sp_in_progress
    state archery_fire_fp_done
    state archery_fire_sp_done
}
state assignment_fork <<fork>>
state assignment {
    state assignment_actions_fp_in_progress
    state assignment_actions_sp_in_progress
    state assignment_actions_fp_done
    state assignment_actions_sp_done
    state assign_defenders_fp_in_progress
    state assign_attackers_sp_in_progress
}
state skirmish_fork <<fork>>
state skirmish
state regroup
state finished

[*] --> bidding_fork

bidding_fork --> bidding_p1_in_progress
bidding_fork --> bidding_p2_in_progress
bidding_p1_in_progress --> bidding_p1_done
bidding_p2_in_progress --> bidding_p2_done
bidding_p1_done --> setup_fork
bidding_p2_done --> setup_fork

setup_fork --> choosing_fellowship_p1_in_progress
setup_fork --> choosing_fellowship_p2_in_progress
choosing_fellowship_p1_in_progress --> choosing_fellowship_p1_done
choosing_fellowship_p2_in_progress --> choosing_fellowship_p2_done
choosing_fellowship_p1_done --> start_turn_fork
choosing_fellowship_p2_done --> start_turn_fork
start_turn_fork --> resolve_start_turn_triggers_fp_in_progress

resolve_start_turn_triggers_fp_in_progress --> fellowship_fork

fellowship_fork --> resolve_start_fellowship_triggers_fp_in_progress
resolve_start_fellowship_triggers_fp_in_progress --> fellowship_actions_fp_in_progress
fellowship_actions_fp_in_progress --> resolve_move_triggers_fp_in_progress
resolve_move_triggers_fp_in_progress --> shadow_fork

shadow_fork --> shadow_actions_sp_in_progress
shadow_actions_sp_in_progress --> maneuver_fork

maneuver_fork --> maneuver_actions_fp_in_progress
maneuver_fork --> maneuver_actions_sp_in_progress
maneuver_actions_fp_in_progress --> maneuver_actions_fp_done
maneuver_actions_sp_in_progress --> maneuver_actions_sp_done
maneuver_actions_fp_done --> archery_fork
maneuver_actions_sp_done --> archery_fork

archery_fork --> archery_actions_fp_in_progress
archery_actions_fp_in_progress --> archery_actions_fp_done
archery_actions_sp_in_progress --> archery_actions_sp_done
archery_actions_fp_done --> archery_fire_fp_in_progress
archery_actions_sp_done --> archery_fire_sp_in_progress
archery_fire_fp_in_progress --> archery_fire_fp_done
archery_fire_sp_in_progress --> archery_fire_sp_done
archery_fire_fp_done --> assignment_fork
archery_fire_sp_done --> assignment_fork

assignment_fork --> assignment_actions_fp_in_progress
assignment_fork --> assignment_actions_sp_in_progress
assignment_actions_fp_in_progress --> assignment_actions_fp_done
assignment_actions_sp_in_progress --> assignment_actions_sp_done
assignment_actions_fp_done --> assign_defenders_fp_in_progress
assignment_actions_sp_done --> assign_defenders_fp_in_progress
assign_defenders_fp_in_progress --> assign_attackers_sp_in_progress

assign_attackers_sp_in_progress --> skirmish
skirmish --> regroup
regroup --> finished
regroup -up-> resolve_start_turn_triggers_fp_in_progress


finished --> [*]

@enduml
