@startuml
hide empty description

state bid_tokens
bid_tokens: Both players bid twilight tokens to decide who starts
bid_tokens --> choose_fellowship

state choose_fellowship
choose_fellowship: Both players play companions for a total of 4 or less
choose_fellowship --> resolve_turn_start

state resolve_turn_start
resolve_turn_start: "At the start of each of your turns" triggers
resolve_turn_start --> resolve_fellowship_start

state resolve_fellowship_start
resolve_fellowship_start: "At the start of each fellowship phase" triggers
resolve_fellowship_start --> perform_fellowship_actions_freeps

state perform_fellowship_actions_freeps
perform_fellowship_actions_freeps: Freeps players may play cards and perform "Fellowship" actions
perform_fellowship_actions_freeps --> resolve_move_triggers_freeps

state resolve_move_triggers_freeps
resolve_move_triggers_freeps: "Each time the fellowship moves" triggers
resolve_move_triggers_freeps --> resolve_shadow_start

state resolve_shadow_start
resolve_shadow_start: "At the beginning of each of your Shadow phases" triggers
resolve_shadow_start --> perform_shadow_actions_shadow

state perform_shadow_actions_shadow
perform_shadow_actions_shadow: Shadow player may play cards and perform "Shadow" actions
perform_shadow_actions_shadow --> resolve_maneuver_start
perform_shadow_actions_shadow -[dotted]-> resolve_regroup_start

state resolve_maneuver_start
resolve_maneuver_start --> perform_maneuver_actions

state perform_maneuver_actions
perform_maneuver_actions: Starting with the Freeps player, both players may perform "Maneuver" actions
perform_maneuver_actions --> resolve_archery_start
perform_maneuver_actions -[dotted]-> resolve_regroup_start

state resolve_archery_start
resolve_archery_start --> perform_archery_actions

state perform_archery_actions
perform_archery_actions: Starting with the Freeps player, both players may perform "Archery" actions
perform_archery_actions --> resolve_archery_fire

state resolve_archery_fire
resolve_archery_fire: Both players assign wounds from archery fire
resolve_archery_fire --> resolve_assignment_start
resolve_archery_fire -[dotted]-> resolve_regroup_start

state resolve_assignment_start
resolve_assignment_start --> perform_assignment_actions

state perform_assignment_actions
perform_assignment_actions: Starting with the Freeps player, both players may perform "Assignment" actions
perform_assignment_actions --> assign_defenders_freeps

state assign_defenders_freeps
assign_defenders_freeps: The Freeps player assigns companions to defend against attacking minions
assign_defenders_freeps --> assign_attackers_shadow
assign_defenders_freeps --> choose_skirmish_freeps

state assign_attackers_shadow
assign_attackers_shadow: The Shadow player assigns leftover minions to companions
assign_attackers_shadow --> choose_skirmish_freeps

state choose_skirmish_freeps
choose_skirmish_freeps: The Freeps player chooses a skirmish to resolve
choose_skirmish_freeps --> resolve_skirmish_start

state resolve_skirmish_start
resolve_skirmish_start --> perform_skirmish_actions

state perform_skirmish_actions
perform_skirmish_actions: Starting with the Freeps player, both players may perform "Skirmish" actions
perform_skirmish_actions --> resolve_skirmish_end

state resolve_skirmish_end
resolve_skirmish_end: "At the end of a skirmish" triggers and winning/losing triggers
resolve_skirmish_end --> choose_skirmish_freeps: next
resolve_skirmish_end --> resolve_assignment_start: fierce
resolve_skirmish_end --> resolve_regroup_start

state resolve_regroup_start
resolve_regroup_start: Effects "until the regroup phase" wear off
resolve_regroup_start --> perform_regroup_actions

state perform_regroup_actions
perform_regroup_actions: The Freeps player may perform "Regroup" actions
perform_regroup_actions --> reconcile_hand_shadow

state reconcile_hand_shadow
reconcile_hand_shadow: The Shadow player may discard 1 card
reconcile_hand_shadow --> choose_move_again_freeps: site 1-8
reconcile_hand_shadow --> finished: site 9

state choose_move_again_freeps
choose_move_again_freeps: The Freeps player chooses whether to move again if possible
choose_move_again_freeps --> reconcile_hand_freeps
choose_move_again_freeps --> resolve_shadow_start: move again

state reconcile_hand_freeps
reconcile_hand_freeps: The Freeps player may discard 1 card
reconcile_hand_freeps --> resolve_turn_end

state resolve_turn_end
resolve_turn_end: Effects "until the end of turn" wear off
resolve_turn_end --> resolve_turn_start

state finished
finished --> [*]



@enduml
