services:
    App\Notifier\NotifierInterface:
        class: App\Notifier\LoggerNotifier
        arguments:
            - '@monolog.logger.notification'
    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'
